### ISSUE TITLE
Include statement is not allowed within a workflow definition

### ISSUE THREAD

**Issue by gianfilippo** [vib-singlecell-nf/vsn-pipelines#372] opened 2022-01-28 20:47 UTC
Hi,

I am just running the 10k PBMCs (10x Genomics) to test the nextflow pipeline.

I get the following error
Include statement is not allowed within a workflow definition

From the log file it looks like nextflow/Java related. I did run another nextflow based pipeline without any issues, though
Perhaps, I may be missing something in the config file, not sure.

Any suggestions ?

Thanks

**Comment by KrisDavie** [comment] 2022-01-31 08:49
Duplicate of https://github.com/vib-singlecell-nf/vsn-pipelines/issues/369

The version lock will be stricter in future updates

**Closed by KrisDavie** 2022-01-31 08:49 UTC
Labels: duplicate
